name: Health Report

on:
  schedule:
    - cron: "13 22,3,10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Report Start
        env:
          users: ${{ secrets.USERS }}
          send: ${{ secrets.SEND }}
        run: "python main.py gh"
